name: Test

env:
  JAVA_DISTRIBUTION: 'temurin'
  JAVA_VERSION: '17'

on:
  push:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven' # Caches dependencies to speed up builds

      - name: Run tests
        run: mvn test
